services:
  db:
    image: postgres
    volumes:
      - .././DB:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  backend:
    build: .
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.scheluded.schedule: "0 0 1 * *"
      ofelia.job-exec.scheluded.command: "python manage.py check_updates"

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - backend
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
