services:
  db:
    image: postgres
    volumes:
      - .././DB:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_greeny
      - POSTGRES_USER=greeny
      - POSTGRES_PASSWORD=GreenyPES24;
    ports:
     - "5432:5432"

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 && python manage.py migrate
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
