name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
            cd Backend
            docker build . --tag ghcr.io/miqueelamorin/hello-docker-gcr-demo:latest
            docker run ghcr.io/miqueelamorin/hello-docker-gcr-demo:latest
            docker push ghcr.io/miqueelamorin/hello-docker-gcr-demo:latest
