name: Docker Image CI

on:
  push:
    branches: [ "main", "develop"]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install System Dependencies
      run: |
        sudo add-apt-repository -y ppa:ubuntugis/ppa
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev
        export CPLUS_INCLUDE_PATH=/usr/include/gdal
        export C_INCLUDE_PATH=/usr/include/gdal

    - name: Install GDAL Python Package
      run: |
        pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==3.3.0

    - name: Install Python Dependencies
      working-directory: Backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install braintree mysqlclient apprise
          
    - name: Run migrations
      run: |
        cd Backend
        python manage.py makemigrations
        ls api/migrations/

    - name: Commit and push migrations
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Add migrations"
        git push
      if: github.ref == 'refs/heads/main'
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
            cd Backend
            docker build . --tag ghcr.io/pes2324q2-gei-upc/greeny:${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
            docker run ghcr.io/pes2324q2-gei-upc/greeny:${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
            docker push ghcr.io/pes2324q2-gei-upc/greeny:${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
