name: Pylint

on:
    push:
    pull_request:
       

jobs:
    pylint:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.x

            - name: Install dependencies
              run: |
                pip install pylint
                pip install pylint-django
                pip install -r ./Backend/requirements.txt
    

            - name: Run Pylint
              run: pylint Backend/greeny --load-plugins pylint_django --disable=missing-class-docstring,missing-function-docstring,missing-module-docstring,too-many-ancestors,no-member
            
            - name: Run Pylint API
              run: pylint --load-plugins pylint_django --disable=missing-class-docstring,missing-function-docstring,missing-module-docstring,too-many-ancestors,no-member --ignore=migrations api

            - name: Run Pylint manage.py
              run: pylint Backend/manage.py --load-plugins pylint_django --disable=missing-class-docstring,missing-function-docstring,missing-module-docstring,too-many-ancestors,no-member
