name: Pylint

on:
    push:

    pull_request:
       

jobs:
    pylint:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.x

            - name: Install dependencies
              run: |
                pip install pylint
                pip install -r ./Backend/requirements.txt
    

            - name: Run Pylint
              run: pylint Backend/greeny --disable=missing-class-docstring,missing-function-docstring 
            
            - name: Run Pylint API
              run: pylint --disable=missing-class-docstring,missing-function-docstring --ignore=migrations Backend/api 

            - name: Run Pylint manage.py
              run: pylint Backend/manage.py --disable=missing-class-docstring,missing-function-docstring
